# fly.toml app configuration file generated for mvp2pocus on 2023-07-04T10:30:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mvp2pocus"
primary_region = "sea"

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
[build]
  [build.args]
    NODE_VERSION = "17"